{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "6cd67a95_034ff2dc",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1561651
      },
      "writtenOn": "2022-12-21T00:27:00Z",
      "side": 1,
      "message": "This is already granted for domain (http://cs/android-internal/system/sepolicy/public/domain.te;l\u003d121;rcl\u003dd5349acab649f35dbd7340ee8c031b48fc1fba30).\n\nDid you have an explicit error to access that directory? Please share the log of the denial to help debug. Thanks.",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "b962562d_52478795",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1893966
      },
      "writtenOn": "2022-12-21T00:41:18Z",
      "side": 1,
      "message": "The presubmit is failing with these errors: https://android-build.googleplex.com/builds/tests/view?invocationId\u003dI68500010118676528\u0026testResultId\u003dTR00728429932829249. I thought that the tagging from apex/com.android.conscrypt-file_contexts wasn\u0027t working because that was not searchable. What should I do to fix this?",
      "parentUuid": "6cd67a95_034ff2dc",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "ed856ce9_8577ef1d",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1561651
      },
      "writtenOn": "2022-12-21T03:12:03Z",
      "side": 1,
      "message": "I think you might not be looking at the correct path. For the apex installed in /apex/com.android.conscrypt... the permissions should already be correct. In the other change you are looking at /data/apex/...",
      "parentUuid": "b962562d_52478795",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "fe5f6ebc_ea3ea7e8",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1893966
      },
      "writtenOn": "2022-12-21T04:42:44Z",
      "side": 1,
      "message": "Oh, ok. I changed the other one but that still does not affect the presubmit. All of the new certificates are within /apex/com.android.conscrypt/cacerts/ and that code was just trying to load them.",
      "parentUuid": "ed856ce9_8577ef1d",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5a3443b9_2313c35e",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1561651
      },
      "writtenOn": "2022-12-21T05:36:23Z",
      "side": 1,
      "message": "There is another reference to the /data path in your other change in TrustedCertificateStore.java. This might be the issue.\n\nThe directories in /apex/com.android.conscrypt/ are already labelled with system_file and as we saw system_security_cacerts_file is also accessible. You really shouldn\u0027t have to add any rule here.\n\nYou can also check out https://source.android.com/docs/security/features/selinux/validate#dumping_user_and_kernel_stacks if the problem persists.",
      "parentUuid": "fe5f6ebc_ea3ea7e8",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a347a918_f36caca0",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1893966
      },
      "writtenOn": "2022-12-21T06:47:23Z",
      "side": 1,
      "message": "ok, thanks. I\u0027ve removed those references and deleted this part of the change. Hopefully that works.",
      "parentUuid": "5a3443b9_2313c35e",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "a75b3574_0cb0c87d",
        "filename": "private/system_app.te",
        "patchSetId": 3
      },
      "lineNbr": 28,
      "author": {
        "id": 1334152
      },
      "writtenOn": "2022-12-21T15:50:50Z",
      "side": 1,
      "message": "Yeah, I can\u0027t reproduce the selinux denials with the latest patchsets.",
      "parentUuid": "a347a918_f36caca0",
      "revId": "1fd442d4fd15984caaa9fb9e4b8595e547321231",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}