{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "d3b83ab0_8ef5ff49",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1060831
      },
      "writtenOn": "2023-11-27T09:14:35Z",
      "side": 1,
      "message": "Thanks for doing this!",
      "revId": "8bb77fe17be22bca0e5fb9df4ad07507cb63274f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "81557aad_10321688",
        "filename": "private/virtualizationmanager.te",
        "patchSetId": 2
      },
      "lineNbr": 102,
      "author": {
        "id": 1060831
      },
      "writtenOn": "2023-11-27T09:14:35Z",
      "side": 1,
      "message": "Looking at system/sepolicy/public/fastbootd.te, I think the exception for fastbootd can be\nrecovery_only(userdebug_or_eng(...)) \n?",
      "range": {
        "startLine": 101,
        "startChar": 0,
        "endLine": 102,
        "endChar": 33
      },
      "revId": "8bb77fe17be22bca0e5fb9df4ad07507cb63274f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}