{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "f7e6667c_0206d501",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 1827146
      },
      "writtenOn": "2021-02-09T21:00:36Z",
      "side": 1,
      "message": "Applied the -system_server exception",
      "revId": "c8686c79b8071d084c5432459a3388ec51d95835",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}