{
  "comments": [
    {
      "key": {
        "uuid": "dfbda2a2_7c06f6aa",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1120458
      },
      "writtenOn": "2020-01-23T17:40:07Z",
      "side": 1,
      "message": "from email, you said you saw:\nStatus(EX_TRANSACTION_FAILED): \u0027FAILED_TRANSACTION: \u0027\n\nWaiting on the resolution there, but assuming that this does work only for some instances?",
      "revId": "e4486c806945fcb54a64aecf3e23c44dd7413bf2",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3bdbdc14_37753490",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 12,
      "author": {
        "id": 1497460
      },
      "writtenOn": "2020-02-05T16:37:17Z",
      "side": 1,
      "message": "With the changes in dumpstate.te the error messages disappeared",
      "parentUuid": "dfbda2a2_7c06f6aa",
      "revId": "e4486c806945fcb54a64aecf3e23c44dd7413bf2",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}